name: Run Gradle Build
on:
    - push
    - pull_request

jobs:
    gradle:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout source
                uses: actions/checkout@v4.1.1

            -   name: Setup Java
                uses: actions/setup-java@v4.0.0
                with:
                    distribution: temurin
                    java-version: 17

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3

            -   name: Execute Plugin test
                run: ./gradlew test

            -   name: Execute Example test
                run: |
                    cd example
                    ./gradlew test
